name: "KiBot On-Push Actions"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  # Add Filters Functionality and ability to get specific path to modified project --------------------------
    # paths:
      # - '*.kicad_sch'
      # - '*.kicad_pcb'
      # - 'KiBot/oem_config.kibot.yaml'
  workflow_dispatch:

# Variable Declarations
env:
  changed_schematic_path: __SCAN__
  changed_pcb_path: __SCAN__

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    name: "Run KiBot"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v4
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Get Changed File Paths
      run: |
        # Variable Declarations
        changed_schematic_path_list=()
        changed_pcb_path_list=()

        # Get Changes
          changed_files="$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
          echo $changed_files
        
        detect_kicad_file_changes() {
            # Check for .kicad_sch or .kicad_pcb file extension
            tmp=($changed_files) # literal string to array
            for element in "${tmp[@]}"; do
                if [[ "$element" == *.kicad_sch ]] || [[ "$element" == *.kicad_pcb ]]; then
                return 0  # Found
                fi
            done
            return 1  # Not found
            }

        if detect_kicad_file_changes; then
            echo True
            # Get all changed .kicad_sch and .kicad_pcb files
            tmp=($changed_files) # literal string to array
            for path in "${tmp[@]}"; do
            if [[ "$path" == *.kicad_pcb ]]; then
                changed_pcb_path_list+=("$path")
            elif [[ "$path" == *.kicad_sch ]]; then
                changed_schematic_path_list+=("$path")
            fi
            done
            echo changed_pcb_path_list
            echo changed_schematic_path_list
            # Logic Used to determine paths for kibot
        else
            echo False
            # if none, then skip kibot actions
        fi
  
  # Actually Run KiBot
    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k9
      with:
      # Remove Hard Coded Paths -----------------------------------------------
        config: 'kibot/oem_config.kibot.yaml'
        schema: $changed_schematic_path
        board: ${{env.changed_pcb_path_list}}

  # Package up all files created by KiBot
    - name: KiBot Files Packaging
      run: |
        zip -r kibot_output.zip /home/runner/work/kibot-automation-testing/kibot-automation-testing/kibot_output

  # Send email with kibot files (diff checker and things)
    - name: Send mail
      uses: dawidd6/action-send-mail@v6
      with:
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.HNTD_TESTING_FROM_EMAIL}}
        # Optional (recommended) mail server password:
        password: ${{secrets.HNTD_TESTING_FROM_EMAIL_PASSWORD}}
        # Required mail subject:
        subject: Automatically Generated KiBot Data - Commit ${{github.event.head_commit.id}}
        # Required recipients' addresses:
        to: ${{github.event.pusher.name}} <${{github.event.pusher.email}}>
        # Required sender full name (address can be skipped):
        from: GitHub Actions Testing <${{secrets.HNTD_TESTING_FROM_EMAIL}}>
        # Optional plain body:
        body: KiBot Automatically Generated Data is Attached. This is an automatically generated message. Commit Information ... Commit Author - ${{github.event.pusher.name}}; Commit Time - ${{github.event.head_commit.timestamp}}; Commit ID - ${{github.event.head_commit.id}}; Commit Message - ${{github.event.head_commit.message}}
        # Optional carbon copy recipients:
        cc: Olin Electric Motorsports <${{secrets.TESTING_OEM_EMAIL}}>
        # Optional blind carbon copy recipients:
        # bcc: 
        # Optional recipient of the email response:
        reply_to: ${{secrets.TESTING_FROM_EMAIL}}
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: /home/runner/work/kibot-automation-testing/kibot-automation-testing/kibot_output.zip
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal
