name: "KiBot On-Push Actions"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  # Add Filters Functionality and ability to get specific path to modified project --------------------------
    # paths:
      # - '*.kicad_sch'
      # - '*.kicad_pcb'
      # - 'KiBot/oem_config.kibot.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v4
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Get Changed File Paths
      run: |
          echo "${{ toJson(github.event.commits) }}" | jq -r '.[].modified[]' > changed_files.txt
          cat changed_files.txt

    - name: Tmp
      uses: actions/upload-artifact@v4
      with:
        name: Automatic_outputs
        path: /home/runner/work/kibot-automation-testing/kibot-automation-testing/changed_files.txt
    
    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k9
      with:
      # Remove Hard Coded Paths -----------------------------------------------
        config: 'testing/oem_config.kibot.yaml'
        schema: 'testing/testing.kicad_sch'
        board: 'testing/testing.kicad_pcb'

    - name: KiBot Files Packaging
      run: |
        zip -r kibot_output.zip /home/runner/work/kibot-automation-testing/kibot-automation-testing/kibot_output

  # Send email with kibot files (diff checker and things)
    - name: Send mail
      uses: dawidd6/action-send-mail@v6
      with:
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.HNTD_TESTING_FROM_EMAIL}}
        # Optional (recommended) mail server password:
        password: ${{secrets.HNTD_TESTING_FROM_EMAIL_PASSWORD}}
        # Required mail subject:
        subject: Automatically Generated KiBot Data - Commit ${{github.event.head_commit.id}}
        # Required recipients' addresses:
        to: ${{github.event.pusher.email}}
        # Required sender full name (address can be skipped):
        from: GitHub Actions Testing <${{secrets.HNTD_TESTING_FROM_EMAIL}}>
        # Optional plain body:
        body: KiBot Automatically Generated Data is Attached. This is an automatically generated message. Commit Information ... Commit Author - ${{github.event.pusher.name}}; Commit Time - ${{github.event.head_commit.timestamp}}; Commit ID - ${{github.event.head_commit.id}}; Commit Message - ${{github.event.head_commit.message}}
        # Optional carbon copy recipients:
        cc: ${{secrets.TESTING_OEM_EMAIL}}
        # Optional blind carbon copy recipients:
        # bcc: 
        # Optional recipient of the email response:
        reply_to: ${{secrets.TESTING_FROM_EMAIL}}
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: /home/runner/work/kibot-automation-testing/kibot-automation-testing/kibot_output.zip
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal
